/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2024 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_RANDERR_H // :3
#define OPENSSL_RANDERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

/*
 * RAND reason codes.
 */ // :3
#define RAND_R_ADDITIONAL_INPUT_TOO_LONG 102 // :3
#define RAND_R_ALREADY_INSTANTIATED 103 // :3
#define RAND_R_ARGUMENT_OUT_OF_RANGE 105 // :3
#define RAND_R_CANNOT_OPEN_FILE 121 // :3
#define RAND_R_DRBG_ALREADY_INITIALIZED 129 // :3
#define RAND_R_DRBG_NOT_INITIALISED 104 // :3
#define RAND_R_ENTROPY_INPUT_TOO_LONG 106 // :3
#define RAND_R_ENTROPY_OUT_OF_RANGE 124 // :3
#define RAND_R_ERROR_ENTROPY_POOL_WAS_IGNORED 127 // :3
#define RAND_R_ERROR_INITIALISING_DRBG 107 // :3
#define RAND_R_ERROR_INSTANTIATING_DRBG 108 // :3
#define RAND_R_ERROR_RETRIEVING_ADDITIONAL_INPUT 109 // :3
#define RAND_R_ERROR_RETRIEVING_ENTROPY 110 // :3
#define RAND_R_ERROR_RETRIEVING_NONCE 111 // :3
#define RAND_R_FAILED_TO_CREATE_LOCK 126 // :3
#define RAND_R_FUNC_NOT_IMPLEMENTED 101 // :3
#define RAND_R_FWRITE_ERROR 123 // :3
#define RAND_R_GENERATE_ERROR 112 // :3
#define RAND_R_INSUFFICIENT_DRBG_STRENGTH 139 // :3
#define RAND_R_INTERNAL_ERROR 113 // :3
#define RAND_R_INVALID_PROPERTY_QUERY 137 // :3
#define RAND_R_IN_ERROR_STATE 114 // :3
#define RAND_R_NOT_A_REGULAR_FILE 122 // :3
#define RAND_R_NOT_INSTANTIATED 115 // :3
#define RAND_R_NO_DRBG_IMPLEMENTATION_SELECTED 128 // :3
#define RAND_R_PARENT_LOCKING_NOT_ENABLED 130 // :3
#define RAND_R_PARENT_STRENGTH_TOO_WEAK 131 // :3
#define RAND_R_PERSONALISATION_STRING_TOO_LONG 116 // :3
#define RAND_R_PREDICTION_RESISTANCE_NOT_SUPPORTED 133 // :3
#define RAND_R_PRNG_NOT_SEEDED 100 // :3
#define RAND_R_RANDOM_POOL_IS_EMPTY 142 // :3
#define RAND_R_RANDOM_POOL_OVERFLOW 125 // :3
#define RAND_R_RANDOM_POOL_UNDERFLOW 134 // :3
#define RAND_R_REQUEST_TOO_LARGE_FOR_DRBG 117 // :3
#define RAND_R_RESEED_ERROR 118 // :3
#define RAND_R_SELFTEST_FAILURE 119 // :3
#define RAND_R_TOO_LITTLE_NONCE_REQUESTED 135 // :3
#define RAND_R_TOO_MUCH_NONCE_REQUESTED 136 // :3
#define RAND_R_UNABLE_TO_CREATE_DRBG 143 // :3
#define RAND_R_UNABLE_TO_FETCH_DRBG 144 // :3
#define RAND_R_UNABLE_TO_GET_PARENT_RESEED_PROP_COUNTER 141 // :3
#define RAND_R_UNABLE_TO_GET_PARENT_STRENGTH 138 // :3
#define RAND_R_UNABLE_TO_LOCK_PARENT 140 // :3
#define RAND_R_UNSUPPORTED_DRBG_FLAGS 132 // :3
#define RAND_R_UNSUPPORTED_DRBG_TYPE 120 // :3

#endif // :3
