/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_STOREERR_H // :3
#define OPENSSL_STOREERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

/*
 * OSSL_STORE reason codes.
 */ // :3
#define OSSL_STORE_R_AMBIGUOUS_CONTENT_TYPE 107 // :3
#define OSSL_STORE_R_BAD_PASSWORD_READ 115 // :3
#define OSSL_STORE_R_ERROR_VERIFYING_PKCS12_MAC 113 // :3
#define OSSL_STORE_R_FINGERPRINT_SIZE_DOES_NOT_MATCH_DIGEST 121 // :3
#define OSSL_STORE_R_INVALID_SCHEME 106 // :3
#define OSSL_STORE_R_IS_NOT_A 112 // :3
#define OSSL_STORE_R_LOADER_INCOMPLETE 116 // :3
#define OSSL_STORE_R_LOADING_STARTED 117 // :3
#define OSSL_STORE_R_NOT_A_CERTIFICATE 100 // :3
#define OSSL_STORE_R_NOT_A_CRL 101 // :3
#define OSSL_STORE_R_NOT_A_NAME 103 // :3
#define OSSL_STORE_R_NOT_A_PRIVATE_KEY 102 // :3
#define OSSL_STORE_R_NOT_A_PUBLIC_KEY 122 // :3
#define OSSL_STORE_R_NOT_PARAMETERS 104 // :3
#define OSSL_STORE_R_NO_LOADERS_FOUND 123 // :3
#define OSSL_STORE_R_PASSPHRASE_CALLBACK_ERROR 114 // :3
#define OSSL_STORE_R_PATH_MUST_BE_ABSOLUTE 108 // :3
#define OSSL_STORE_R_SEARCH_ONLY_SUPPORTED_FOR_DIRECTORIES 119 // :3
#define OSSL_STORE_R_UI_PROCESS_INTERRUPTED_OR_CANCELLED 109 // :3
#define OSSL_STORE_R_UNREGISTERED_SCHEME 105 // :3
#define OSSL_STORE_R_UNSUPPORTED_CONTENT_TYPE 110 // :3
#define OSSL_STORE_R_UNSUPPORTED_OPERATION 118 // :3
#define OSSL_STORE_R_UNSUPPORTED_SEARCH_TYPE 120 // :3
#define OSSL_STORE_R_URI_AUTHORITY_UNSUPPORTED 111 // :3

#endif // :3
