/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2024 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_X509ERR_H // :3
#define OPENSSL_X509ERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

/*
 * X509 reason codes.
 */ // :3
#define X509_R_AKID_MISMATCH 110 // :3
#define X509_R_BAD_SELECTOR 133 // :3
#define X509_R_BAD_X509_FILETYPE 100 // :3
#define X509_R_BASE64_DECODE_ERROR 118 // :3
#define X509_R_CANT_CHECK_DH_KEY 114 // :3
#define X509_R_CERTIFICATE_VERIFICATION_FAILED 139 // :3
#define X509_R_CERT_ALREADY_IN_HASH_TABLE 101 // :3
#define X509_R_CRL_ALREADY_DELTA 127 // :3
#define X509_R_CRL_VERIFY_FAILURE 131 // :3
#define X509_R_DUPLICATE_ATTRIBUTE 140 // :3
#define X509_R_ERROR_GETTING_MD_BY_NID 141 // :3
#define X509_R_ERROR_USING_SIGINF_SET 142 // :3
#define X509_R_IDP_MISMATCH 128 // :3
#define X509_R_INVALID_ATTRIBUTES 138 // :3
#define X509_R_INVALID_DIRECTORY 113 // :3
#define X509_R_INVALID_DISTPOINT 143 // :3
#define X509_R_INVALID_FIELD_NAME 119 // :3
#define X509_R_INVALID_TRUST 123 // :3
#define X509_R_ISSUER_MISMATCH 129 // :3
#define X509_R_KEY_TYPE_MISMATCH 115 // :3
#define X509_R_KEY_VALUES_MISMATCH 116 // :3
#define X509_R_LOADING_CERT_DIR 103 // :3
#define X509_R_LOADING_DEFAULTS 104 // :3
#define X509_R_METHOD_NOT_SUPPORTED 124 // :3
#define X509_R_NAME_TOO_LONG 134 // :3
#define X509_R_NEWER_CRL_NOT_NEWER 132 // :3
#define X509_R_NO_CERTIFICATE_FOUND 135 // :3
#define X509_R_NO_CERTIFICATE_OR_CRL_FOUND 136 // :3
#define X509_R_NO_CERT_SET_FOR_US_TO_VERIFY 105 // :3
#define X509_R_NO_CRL_FOUND 137 // :3
#define X509_R_NO_CRL_NUMBER 130 // :3
#define X509_R_PUBLIC_KEY_DECODE_ERROR 125 // :3
#define X509_R_PUBLIC_KEY_ENCODE_ERROR 126 // :3
#define X509_R_SHOULD_RETRY 106 // :3
#define X509_R_UNABLE_TO_FIND_PARAMETERS_IN_CHAIN 107 // :3
#define X509_R_UNABLE_TO_GET_CERTS_PUBLIC_KEY 108 // :3
#define X509_R_UNKNOWN_KEY_TYPE 117 // :3
#define X509_R_UNKNOWN_NID 109 // :3
#define X509_R_UNKNOWN_PURPOSE_ID 121 // :3
#define X509_R_UNKNOWN_SIGID_ALGS 144 // :3
#define X509_R_UNKNOWN_TRUST_ID 120 // :3
#define X509_R_UNSUPPORTED_ALGORITHM 111 // :3
#define X509_R_UNSUPPORTED_VERSION 145 // :3
#define X509_R_WRONG_LOOKUP_TYPE 112 // :3
#define X509_R_WRONG_TYPE 122 // :3

#endif // :3
