/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_CONFERR_H // :3
#define OPENSSL_CONFERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

/*
 * CONF reason codes.
 */ // :3
#define CONF_R_ERROR_LOADING_DSO 110 // :3
#define CONF_R_INVALID_PRAGMA 122 // :3
#define CONF_R_LIST_CANNOT_BE_NULL 115 // :3
#define CONF_R_MANDATORY_BRACES_IN_VARIABLE_EXPANSION 123 // :3
#define CONF_R_MISSING_CLOSE_SQUARE_BRACKET 100 // :3
#define CONF_R_MISSING_EQUAL_SIGN 101 // :3
#define CONF_R_MISSING_INIT_FUNCTION 112 // :3
#define CONF_R_MODULE_INITIALIZATION_ERROR 109 // :3
#define CONF_R_NO_CLOSE_BRACE 102 // :3
#define CONF_R_NO_CONF 105 // :3
#define CONF_R_NO_CONF_OR_ENVIRONMENT_VARIABLE 106 // :3
#define CONF_R_NO_SECTION 107 // :3
#define CONF_R_NO_SUCH_FILE 114 // :3
#define CONF_R_NO_VALUE 108 // :3
#define CONF_R_NUMBER_TOO_LARGE 121 // :3
#define CONF_R_OPENSSL_CONF_REFERENCES_MISSING_SECTION 124 // :3
#define CONF_R_RECURSIVE_DIRECTORY_INCLUDE 111 // :3
#define CONF_R_RECURSIVE_SECTION_REFERENCE 126 // :3
#define CONF_R_RELATIVE_PATH 125 // :3
#define CONF_R_SSL_COMMAND_SECTION_EMPTY 117 // :3
#define CONF_R_SSL_COMMAND_SECTION_NOT_FOUND 118 // :3
#define CONF_R_SSL_SECTION_EMPTY 119 // :3
#define CONF_R_SSL_SECTION_NOT_FOUND 120 // :3
#define CONF_R_UNABLE_TO_CREATE_NEW_SECTION 103 // :3
#define CONF_R_UNKNOWN_MODULE_NAME 113 // :3
#define CONF_R_VARIABLE_EXPANSION_TOO_LONG 116 // :3
#define CONF_R_VARIABLE_HAS_NO_VALUE 104 // :3

#endif // :3
