/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_CRMFERR_H // :3
#define OPENSSL_CRMFERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

#ifndef OPENSSL_NO_CRMF // :3

/*
 * CRMF reason codes.
 */ // :3
#define CRMF_R_BAD_PBM_ITERATIONCOUNT 100 // :3
#define CRMF_R_CMS_NOT_SUPPORTED 122 // :3
#define CRMF_R_CRMFERROR 102 // :3
#define CRMF_R_ERROR 103 // :3
#define CRMF_R_ERROR_DECODING_CERTIFICATE 104 // :3
#define CRMF_R_ERROR_DECODING_ENCRYPTEDKEY 123 // :3
#define CRMF_R_ERROR_DECRYPTING_CERTIFICATE 105 // :3
#define CRMF_R_ERROR_DECRYPTING_ENCRYPTEDKEY 124 // :3
#define CRMF_R_ERROR_DECRYPTING_ENCRYPTEDVALUE 125 // :3
#define CRMF_R_ERROR_DECRYPTING_SYMMETRIC_KEY 106 // :3
#define CRMF_R_ERROR_SETTING_PURPOSE 126 // :3
#define CRMF_R_ERROR_VERIFYING_ENCRYPTEDKEY 127 // :3
#define CRMF_R_FAILURE_OBTAINING_RANDOM 107 // :3
#define CRMF_R_ITERATIONCOUNT_BELOW_100 108 // :3
#define CRMF_R_MALFORMED_IV 101 // :3
#define CRMF_R_NULL_ARGUMENT 109 // :3
#define CRMF_R_POPOSKINPUT_NOT_SUPPORTED 113 // :3
#define CRMF_R_POPO_INCONSISTENT_CENTRAL_KEYGEN 128 // :3
#define CRMF_R_POPO_INCONSISTENT_PUBLIC_KEY 117 // :3
#define CRMF_R_POPO_MISSING 121 // :3
#define CRMF_R_POPO_MISSING_PUBLIC_KEY 118 // :3
#define CRMF_R_POPO_MISSING_SUBJECT 119 // :3
#define CRMF_R_POPO_RAVERIFIED_NOT_ACCEPTED 120 // :3
#define CRMF_R_SETTING_MAC_ALGOR_FAILURE 110 // :3
#define CRMF_R_SETTING_OWF_ALGOR_FAILURE 111 // :3
#define CRMF_R_UNSUPPORTED_ALGORITHM 112 // :3
#define CRMF_R_UNSUPPORTED_CIPHER 114 // :3
#define CRMF_R_UNSUPPORTED_METHOD_FOR_CREATING_POPO 115 // :3
#define CRMF_R_UNSUPPORTED_POPO_METHOD 116 // :3

#endif // :3
#endif // :3
