/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_ENGINEERR_H // :3
#define OPENSSL_ENGINEERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

#ifndef OPENSSL_NO_ENGINE // :3

/*
 * ENGINE reason codes.
 */ // :3
#define ENGINE_R_ALREADY_LOADED 100 // :3
#define ENGINE_R_ARGUMENT_IS_NOT_A_NUMBER 133 // :3
#define ENGINE_R_CMD_NOT_EXECUTABLE 134 // :3
#define ENGINE_R_COMMAND_TAKES_INPUT 135 // :3
#define ENGINE_R_COMMAND_TAKES_NO_INPUT 136 // :3
#define ENGINE_R_CONFLICTING_ENGINE_ID 103 // :3
#define ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED 119 // :3
#define ENGINE_R_DSO_FAILURE 104 // :3
#define ENGINE_R_DSO_NOT_FOUND 132 // :3
#define ENGINE_R_ENGINES_SECTION_ERROR 148 // :3
#define ENGINE_R_ENGINE_CONFIGURATION_ERROR 102 // :3
#define ENGINE_R_ENGINE_IS_NOT_IN_LIST 105 // :3
#define ENGINE_R_ENGINE_SECTION_ERROR 149 // :3
#define ENGINE_R_FAILED_LOADING_PRIVATE_KEY 128 // :3
#define ENGINE_R_FAILED_LOADING_PUBLIC_KEY 129 // :3
#define ENGINE_R_FINISH_FAILED 106 // :3
#define ENGINE_R_ID_OR_NAME_MISSING 108 // :3
#define ENGINE_R_INIT_FAILED 109 // :3
#define ENGINE_R_INTERNAL_LIST_ERROR 110 // :3
#define ENGINE_R_INVALID_ARGUMENT 143 // :3
#define ENGINE_R_INVALID_CMD_NAME 137 // :3
#define ENGINE_R_INVALID_CMD_NUMBER 138 // :3
#define ENGINE_R_INVALID_INIT_VALUE 151 // :3
#define ENGINE_R_INVALID_STRING 150 // :3
#define ENGINE_R_NOT_INITIALISED 117 // :3
#define ENGINE_R_NOT_LOADED 112 // :3
#define ENGINE_R_NO_CONTROL_FUNCTION 120 // :3
#define ENGINE_R_NO_INDEX 144 // :3
#define ENGINE_R_NO_LOAD_FUNCTION 125 // :3
#define ENGINE_R_NO_REFERENCE 130 // :3
#define ENGINE_R_NO_SUCH_ENGINE 116 // :3
#define ENGINE_R_UNIMPLEMENTED_CIPHER 146 // :3
#define ENGINE_R_UNIMPLEMENTED_DIGEST 147 // :3
#define ENGINE_R_UNIMPLEMENTED_PUBLIC_KEY_METHOD 101 // :3
#define ENGINE_R_VERSION_INCOMPATIBILITY 145 // :3

#endif // :3
#endif // :3
