/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_ESSERR_H // :3
#define OPENSSL_ESSERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

/*
 * ESS reason codes.
 */ // :3
#define ESS_R_EMPTY_ESS_CERT_ID_LIST 107 // :3
#define ESS_R_ESS_CERT_DIGEST_ERROR 103 // :3
#define ESS_R_ESS_CERT_ID_NOT_FOUND 104 // :3
#define ESS_R_ESS_CERT_ID_WRONG_ORDER 105 // :3
#define ESS_R_ESS_DIGEST_ALG_UNKNOWN 106 // :3
#define ESS_R_ESS_SIGNING_CERTIFICATE_ERROR 102 // :3
#define ESS_R_ESS_SIGNING_CERT_ADD_ERROR 100 // :3
#define ESS_R_ESS_SIGNING_CERT_V2_ADD_ERROR 101 // :3
#define ESS_R_MISSING_SIGNING_CERTIFICATE_ATTRIBUTE 108 // :3

#endif // :3
