/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2025 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_PEMERR_H // :3
#define OPENSSL_PEMERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

/*
 * PEM reason codes.
 */ // :3
#define PEM_R_BAD_BASE64_DECODE 100 // :3
#define PEM_R_BAD_DECRYPT 101 // :3
#define PEM_R_BAD_END_LINE 102 // :3
#define PEM_R_BAD_IV_CHARS 103 // :3
#define PEM_R_BAD_MAGIC_NUMBER 116 // :3
#define PEM_R_BAD_PASSWORD_READ 104 // :3
#define PEM_R_BAD_VERSION_NUMBER 117 // :3
#define PEM_R_BIO_WRITE_FAILURE 118 // :3
#define PEM_R_CIPHER_IS_NULL 127 // :3
#define PEM_R_ERROR_CONVERTING_PRIVATE_KEY 115 // :3
#define PEM_R_EXPECTING_DSS_KEY_BLOB 131 // :3
#define PEM_R_EXPECTING_PRIVATE_KEY_BLOB 119 // :3
#define PEM_R_EXPECTING_PUBLIC_KEY_BLOB 120 // :3
#define PEM_R_EXPECTING_RSA_KEY_BLOB 132 // :3
#define PEM_R_HEADER_TOO_LONG 128 // :3
#define PEM_R_INCONSISTENT_HEADER 121 // :3
#define PEM_R_KEYBLOB_HEADER_PARSE_ERROR 122 // :3
#define PEM_R_KEYBLOB_TOO_SHORT 123 // :3
#define PEM_R_MISSING_DEK_IV 129 // :3
#define PEM_R_NOT_DEK_INFO 105 // :3
#define PEM_R_NOT_ENCRYPTED 106 // :3
#define PEM_R_NOT_PROC_TYPE 107 // :3
#define PEM_R_NO_START_LINE 108 // :3
#define PEM_R_PROBLEMS_GETTING_PASSWORD 109 // :3
#define PEM_R_PVK_DATA_TOO_SHORT 124 // :3
#define PEM_R_PVK_TOO_SHORT 125 // :3
#define PEM_R_READ_KEY 111 // :3
#define PEM_R_SHORT_HEADER 112 // :3
#define PEM_R_UNEXPECTED_DEK_IV 130 // :3
#define PEM_R_UNSUPPORTED_CIPHER 113 // :3
#define PEM_R_UNSUPPORTED_ENCRYPTION 114 // :3
#define PEM_R_UNSUPPORTED_KEY_COMPONENTS 126 // :3
#define PEM_R_UNSUPPORTED_PUBLIC_KEY_TYPE 110 // :3
#define PEM_R_UNSUPPORTED_PVK_KEY_TYPE 133 // :3

#endif // :3
