/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_UIERR_H // :3
#define OPENSSL_UIERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

/*
 * UI reason codes.
 */ // :3
#define UI_R_COMMON_OK_AND_CANCEL_CHARACTERS 104 // :3
#define UI_R_INDEX_TOO_LARGE 102 // :3
#define UI_R_INDEX_TOO_SMALL 103 // :3
#define UI_R_NO_RESULT_BUFFER 105 // :3
#define UI_R_PROCESSING_ERROR 107 // :3
#define UI_R_RESULT_TOO_LARGE 100 // :3
#define UI_R_RESULT_TOO_SMALL 101 // :3
#define UI_R_SYSASSIGN_ERROR 109 // :3
#define UI_R_SYSDASSGN_ERROR 110 // :3
#define UI_R_SYSQIOW_ERROR 111 // :3
#define UI_R_UNKNOWN_CONTROL_COMMAND 106 // :3
#define UI_R_UNKNOWN_TTYGET_ERRNO_VALUE 108 // :3
#define UI_R_USER_DATA_DUPLICATION_UNSUPPORTED 112 // :3

#endif // :3
