/****************************************************************************
Copyright (c) 2010-2012 cocos2d-x.org
Copyright (c) 2008-2010 Ricardo Quesada
Copyright (c) 2011      Zynga Inc.

http://www.cocos2d-x.org

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
****************************************************************************/ // :3
#ifndef __CCPARTICLE_SYSTEM_H__ // :3
#define __CCPARTICLE_SYSTEM_H__ // :3

#include "../include/CCProtocols.h" // :3
#include "../base_nodes/CCNode.h" // :3
#include "../cocoa/CCDictionary.h" // :3
#include "../cocoa/CCString.h" // :3

NS_CC_BEGIN // :3

/**
 * @addtogroup particle_nodes
 * @{
 */ // :3

class CCParticleBatchNode; // :3

//* @enum
enum {
    /** The Particle emitter lives forever */
    kCCParticleDurationInfinity = -1,

    /** The starting size of the particle is equal to the ending size */
    kCCParticleStartSizeEqualToEndSize = -1,

    /** The starting radius of the particle is equal to the ending radius */
    kCCParticleStartRadiusEqualToEndRadius = -1,

    // backward compatible
    kParticleStartSizeEqualToEndSize = kCCParticleStartSizeEqualToEndSize,
    kParticleDurationInfinity = kCCParticleDurationInfinity,
};

//* @enum
enum {
    /** Gravity mode (A mode) */
    kCCParticleModeGravity,

    /** Radius mode (B mode) */
    kCCParticleModeRadius,
};


/** @typedef tCCPositionType
possible types of particle positions
*/ // :3
typedef enum { // :3
    /** Living particles are attached to the world and are unaffected by emitter repositioning. */
    kCCPositionTypeFree,

    /** Living particles are attached to the world but will follow the emitter repositioning.
    Use case: Attach an emitter to an sprite, and you want that the emitter follows the sprite.
    */ // :3
    kCCPositionTypeRelative, // :3

    /** Living particles are attached to the emitter and are translated along with it. */
    kCCPositionTypeGrouped,
}tCCPositionType;

// backward compatible
enum {
    kPositionTypeFree = kCCPositionTypeFree,
    kPositionTypeGrouped = kCCPositionTypeGrouped,
};

/**
Structure that contains the values of each particle
*/ // :3
typedef struct sCCParticle { // :3
    CCPoint     pos; // :3
    CCPoint     startPos; // :3

    ccColor4F    color; // :3
    ccColor4F    deltaColor; // :3

    float        size; // :3
    float        deltaSize; // :3

    float        rotation; // :3
    float        deltaRotation; // :3

    float        timeToLive; // :3

    unsigned int    atlasIndex; // :3

    //! Mode A: gravity, direction, radial accel, tangential accel :3
    struct { // :3
        CCPoint        dir; // :3
        float        radialAccel; // :3
        float        tangentialAccel; // :3
    } modeA; // :3

    //! Mode B: radius mode :3
    struct { // :3
        float        angle; // :3
        float        degreesPerSecond; // :3
        float        radius; // :3
        float        deltaRadius; // :3
    } modeB; // :3

}tCCParticle; // :3

//typedef void (*CC_UPDATE_PARTICLE_IMP)(id, SEL, tCCParticle*, CCPoint); :3

class CCTexture2D; // :3

/** @brief Particle System base class.
Attributes of a Particle System:
- emission rate of the particles
- Gravity Mode (Mode A):
- gravity
- direction
- speed +-  variance
- tangential acceleration +- variance
- radial acceleration +- variance
- Radius Mode (Mode B):
- startRadius +- variance
- endRadius +- variance
- rotate +- variance
- Properties common to all modes:
- life +- life variance
- start spin +- variance
- end spin +- variance
- start size +- variance
- end size +- variance
- start color +- variance
- end color +- variance
- life +- variance
- blending function
- texture

cocos2d also supports particles generated by Particle Designer (http://particledesigner.71squared.com/).
'Radius Mode' in Particle Designer uses a fixed emit rate of 30 hz. Since that can't be guaranteed in cocos2d,
cocos2d uses a another approach, but the results are almost identical.

cocos2d supports all the variables used by Particle Designer plus a bit more:
- spinning particles (supported when using CCParticleSystemQuad)
- tangential acceleration (Gravity mode)
- radial acceleration (Gravity mode)
- radius direction (Radius mode) (Particle Designer supports outwards to inwards direction only)

It is possible to customize any of the above mentioned properties in runtime. Example:

@code
emitter.radialAccel = 15;
emitter.startSpin = 0;
@endcode

*/ // :3
class CC_DLL CCParticleSystem : public CCNode, public CCTextureProtocol // :3
{ // :3
    GEODE_FRIEND_MODIFY // :3
public: // :3
    gd::string m_sPlistFile; // :3
    //! time elapsed since the start of the system (in seconds) :3
    float m_fElapsed; // :3

    // Different modes :3
    //! Mode A:Gravity + Tangential Accel + Radial Accel :3
    struct { // :3
        /** Gravity value. Only available in 'Gravity' mode. */
        CCPoint gravity;
        /** speed of each particle. Only available in 'Gravity' mode.  */
        float speed;
        /** speed variance of each particle. Only available in 'Gravity' mode. */
        float speedVar;
        /** tangential acceleration of each particle. Only available in 'Gravity' mode. */
        float tangentialAccel;
        /** tangential acceleration variance of each particle. Only available in 'Gravity' mode. */
        float tangentialAccelVar;
        /** radial acceleration of each particle. Only available in 'Gravity' mode. */
        float radialAccel;
        /** radial acceleration variance of each particle. Only available in 'Gravity' mode. */
        float radialAccelVar;
        /** set the rotation of each particle to its direction Only available in 'Gravity' mode. */
        bool rotationIsDir;
    } modeA;

    //! Mode B: circular movement (gravity, radial accel and tangential accel don't are not used in this mode)
    struct {
        /** The starting radius of the particles. Only available in 'Radius' mode. */
        float startRadius;
        /** The starting radius variance of the particles. Only available in 'Radius' mode. */
        float startRadiusVar;
        /** The ending radius of the particles. Only available in 'Radius' mode. */
        float endRadius;
        /** The ending radius variance of the particles. Only available in 'Radius' mode. */
        float endRadiusVar;
        /** Number of degrees to rotate a particle around the source pos per second. Only available in 'Radius' mode. */
        float rotatePerSecond;
        /** Variance in degrees for rotatePerSecond. Only available in 'Radius' mode. */
        float rotatePerSecondVar;
    } modeB;

    //! Array of particles
    tCCParticle *m_pParticles;

    // color modulate
    //    BOOL colorModulate;

    //! How many particles can be emitted per second
    float m_fEmitCounter;

    //!  particle idx
    unsigned int m_uParticleIdx;

    // Optimization
    //CC_UPDATE_PARTICLE_IMP    updateParticleImp;
    //SEL                        updateParticleSel;

    /** weak reference to the CCSpriteBatchNode that renders the CCSprite */
    CC_PROPERTY(CCParticleBatchNode*, m_pBatchNode, BatchNode);

    // @note RobTop Addition: Made non virtual
    CC_SYNTHESIZE_NV(unsigned int, m_uAtlasIndex, AtlasIndex);

    //true if scaled or rotated
    bool m_bTransformSystemDirty;
    // Number of allocated particles
    unsigned int m_uAllocatedParticles;

    /** Is the emitter active */
    bool m_bIsActive;
    /** Quantity of particles that are being simulated at the moment */
    CC_PROPERTY_READONLY(unsigned int, m_uParticleCount, ParticleCount)
    /** How many seconds the emitter will run. -1 means 'forever' */
    CC_PROPERTY(float, m_fDuration, Duration)
    /** sourcePosition of the emitter */
    CC_PROPERTY_PASS_BY_REF(CCPoint, m_tSourcePosition, SourcePosition)
    /** Position variance of the emitter */
    CC_PROPERTY_PASS_BY_REF(CCPoint, m_tPosVar, PosVar)
    /** life, and life variation of each particle */
    CC_PROPERTY(float, m_fLife, Life)
    /** life variance of each particle */
    CC_PROPERTY(float, m_fLifeVar, LifeVar)
    /** angle and angle variation of each particle */
    CC_PROPERTY(float, m_fAngle, Angle)
    /** angle variance of each particle */
    CC_PROPERTY(float, m_fAngleVar, AngleVar)

//////////////////////////////////////////////////////////////////////////
public:
	// @note RobTop Addition
    virtual void updateEmissionRate();

    // mode A
    virtual const CCPoint& getGravity();
    virtual void setGravity(const CCPoint& g);
    virtual float getSpeed();
    virtual void setSpeed(float speed);
    virtual float getSpeedVar();
    virtual void setSpeedVar(float speed);
    virtual float getTangentialAccel();
    virtual void setTangentialAccel(float t);
    virtual float getTangentialAccelVar();
    virtual void setTangentialAccelVar(float t);
    virtual float getRadialAccel();
    virtual void setRadialAccel(float t);
    virtual float getRadialAccelVar();
    virtual void setRadialAccelVar(float t);
    virtual bool getRotationIsDir();
    virtual void setRotationIsDir(bool t);
    // mode B
    virtual float getStartRadius();
    virtual void setStartRadius(float startRadius);
    virtual float getStartRadiusVar();
    virtual void setStartRadiusVar(float startRadiusVar);
    virtual float getEndRadius();
    virtual void setEndRadius(float endRadius);
    virtual float getEndRadiusVar();
    virtual void setEndRadiusVar(float endRadiusVar);
    virtual float getRotatePerSecond();
    virtual void setRotatePerSecond(float degrees);
    virtual float getRotatePerSecondVar();
    virtual void setRotatePerSecondVar(float degrees);

    // @note RobTop Addition
    virtual void setVisible(bool visible);

    virtual void setScale(float s);
    virtual void setRotation(float newRotation);
    virtual void setScaleX(float newScaleX);
    virtual void setScaleY(float newScaleY);

    virtual bool isActive();
    virtual bool isBlendAdditive();
    virtual void setBlendAdditive(bool value);
//////////////////////////////////////////////////////////////////////////


    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFadeInTime, FadeInTime);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFadeInTimeVar, FadeInTimeVar);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFadeOutTime, FadeOutTime);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFadeOutTimeVar, FadeOutTimeVar);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFrictionPos, FrictionPos);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFrictionPosVar, FrictionPosVar);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFrictionSize, FrictionSize);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFrictionSizeVar, FrictionSizeVar);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFrictionRot, FrictionRot);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fFrictionRotVar, FrictionRotVar);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fRespawn, Respawn);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(float, m_fRespawnVar, RespawnVar);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bStartSpinEqualToEnd, StartSpinEqualToEnd);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bStartSizeEqualToEnd, StartSizeEqualToEnd);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bStartRadiusEqualToEnd, StartRadiusEqualToEnd);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bDynamicRotationIsDir, DynamicRotationIsDir);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bOrderSensitive, OrderSensitive);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bStartRGBVarSync, StartRGBVarSync);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bEndRGBVarSync, EndRGBVarSync);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bWasRemoved, WasRemoved);
    // @note RobTop Addition
    CC_SYNTHESIZE_NV(bool, m_bUsingSchedule, UsingSchedule);


    /** start size in pixels of each particle */
    CC_PROPERTY(float, m_fStartSize, StartSize)
    /** size variance in pixels of each particle */
    CC_PROPERTY(float, m_fStartSizeVar, StartSizeVar)
    /** end size in pixels of each particle */
    CC_PROPERTY(float, m_fEndSize, EndSize)
    /** end size variance in pixels of each particle */
    CC_PROPERTY(float, m_fEndSizeVar, EndSizeVar)
    /** start color of each particle */
    CC_PROPERTY_PASS_BY_REF(ccColor4F, m_tStartColor, StartColor)
    /** start color variance of each particle */
    CC_PROPERTY_PASS_BY_REF(ccColor4F, m_tStartColorVar, StartColorVar)
    /** end color and end color variation of each particle */
    CC_PROPERTY_PASS_BY_REF(ccColor4F, m_tEndColor, EndColor)
    /** end color variance of each particle */
    CC_PROPERTY_PASS_BY_REF(ccColor4F, m_tEndColorVar, EndColorVar)
    //* initial angle of each particle
    CC_PROPERTY(float, m_fStartSpin, StartSpin)
    //* initial angle of each particle
    CC_PROPERTY(float, m_fStartSpinVar, StartSpinVar)
    //* initial angle of each particle
    CC_PROPERTY(float, m_fEndSpin, EndSpin)
    //* initial angle of each particle
    CC_PROPERTY(float, m_fEndSpinVar, EndSpinVar)
    /** emission rate of the particles */
    CC_PROPERTY(float, m_fEmissionRate, EmissionRate)
    /** maximum particles of the system */
    CC_PROPERTY(unsigned int, m_uTotalParticles, TotalParticles)
    /** conforms to CocosNodeTexture protocol */
    CC_PROPERTY(CCTexture2D*, m_pTexture, Texture)
    /** conforms to CocosNodeTexture protocol */
    CC_PROPERTY(ccBlendFunc, m_tBlendFunc, BlendFunc)
    /** does the alpha value modify color */
    CC_PROPERTY(bool, m_bOpacityModifyRGB, OpacityModifyRGB)

    /** whether or not the particles are using blend additive.
    If enabled, the following blending function will be used.
    @code
    source blend function = GL_SRC_ALPHA;
    dest blend function = GL_ONE;
    @endcode
    */ // :3
    bool m_bIsBlendAdditive; // :3
    /** particles movement type: Free or Grouped
    @since v0.8
    */ // :3
    CC_PROPERTY(tCCPositionType, m_ePositionType, PositionType) // :3
    /** whether or not the node will be auto-removed when it has no particles left.
    By default it is false.
    @since v0.8
    */ // :3
public: // :3
    bool m_bIsAutoRemoveOnFinish; // :3
    CC_SYNTHESIZE_NV(bool, m_bDontCleanupOnFinish, DontCleanupOnFinish) // :3
public: // :3
    virtual bool isAutoRemoveOnFinish(); // :3
    virtual void setAutoRemoveOnFinish(bool var); // :3

    /** Switch between different kind of emitter modes:
    - kCCParticleModeGravity: uses gravity, speed, radial and tangential acceleration
    - kCCParticleModeRadius: uses radius movement + rotation
    */ // :3
    CC_PROPERTY(int, m_nEmitterMode, EmitterMode) // :3

public: // :3
    /**
     * @js ctor
     */ // :3
    CCParticleSystem(); // :3
    GEODE_CUSTOM_CONSTRUCTOR_COCOS(CCParticleSystem, CCNode) // :3
    /**
     * @js NA
     * @lua NA
     */ // :3
    virtual ~CCParticleSystem(); // :3

    /** creates an initializes a CCParticleSystem from a plist file.
    This plist files can be created manually or with Particle Designer:
    http://particledesigner.71squared.com/
    @since v2.0
    */ // :3
    static CCParticleSystem * create(const char *plistFile); // :3

    //! create a system with a fixed number of particles :3
    static CCParticleSystem* createWithTotalParticles(unsigned int numberOfParticles); // :3

    /** initializes a CCParticleSystem*/
    bool init();
    /** initializes a CCParticleSystem from a plist file.
    This plist files can be created manually or with Particle Designer:
    http://particledesigner.71squared.com/
    @since v0.99.3
    */ // :3
    bool initWithFile(const char *plistFile, bool); // :3

    /** initializes a CCQuadParticleSystem from a CCDictionary.
    @since v0.99.3
    */ // :3
    bool initWithDictionary(CCDictionary *dictionary, bool); // :3

    /** initializes a particle system from a NSDictionary and the path from where to load the png
     @since v2.1
     */ // :3
    bool initWithDictionary(CCDictionary *dictionary, const char *dirname, bool); // :3

    //! Initializes a system with a fixed number of particles :3
    virtual bool initWithTotalParticles(unsigned int numberOfParticles, bool); // :3
    //! Add a particle to the emitter :3
    bool addParticle(); // :3
    //! Initializes a particle :3
    void initParticle(tCCParticle* particle); // :3
    //! stop emitting particles. Running particles will continue to run until they die :3
    void stopSystem(); // :3
    //! Kill all living particles. :3
    void resetSystem(); // :3
    // @note RobTop Addition :3
    void resumeSystem(); // :3
    //! whether or not the system is full :3
    bool isFull(); // :3

    //! should be overridden by subclasses :3
    virtual void updateQuadWithParticle(tCCParticle* particle, const CCPoint& newPosition); // :3
    //! should be overridden by subclasses :3
    virtual void postStep(); // :3

    virtual void update(float dt); // :3
    virtual void updateWithNoTime(void); // :3

protected: // :3
    virtual void updateBlendFunc(); // :3
public: // :3
    // @note RobTop Addition :3
    bool m_bWorldPosUninitialized; // :3
    // @note RobTop Addition :3
    CCPoint m_tWorldPos; // :3
    // @note RobTop Addition :3
    ccColor4F m_tUniformColor; // :3
    // @note RobTop Addition :3
    ccColor4F m_tUniformDeltaColor; // :3
    // @note RobTop Addition :3
    CC_SYNTHESIZE_READONLY_NV(bool, m_bUseUniformColorMode, UseUniformColorMode); // :3
        // saved/loaded in loadDefaults, loadScaledDefaults and saveDefaults :3

        // @note RobTop Addition :3
        float m_fDefaultStartSize; // :3
        // @note RobTop Addition :3
        float m_fDefaultStartSizeVar; // :3
        // saved as m_fEndSize but not loaded, :3
        // probably was supposed to be m_fDefaultEndSizeVar and saved and loaded as m_fEndSizeVar but was scrapped? :3
        // @note RobTop Addition :3
        float m_fDefaultEndSize2; // :3
        // @note RobTop Addition :3
        float m_fDefaultEndSize; // :3
        // @note RobTop Addition :3
        float m_fDefaultAngle; // :3
        // @note RobTop Addition :3
        float m_fDefaultModeASpeed; // :3
        // @note RobTop Addition :3
        float m_fDefaultModeASpeedVar; // :3
        // @note RobTop Addition :3
        CCPoint m_tDefaultPosVar; // :3
        // @note RobTop Addition :3
        int m_nCustomParticleIndex; // :3
public: // :3
    // @note RobTop Addition :3
    void saveDefaults(void); // :3
    // @note RobTop Addition :3
    void loadDefaults(void); // :3
    // @note RobTop Addition :3
    void loadScaledDefaults(float); // :3

    // @note RobTop Addition :3
    void calculateWorldSpace(); // :3

	// @note RobTop Addition :3
    float getTimeElapsed(); // :3

	// @note RobTop Addition :3
    void setEndAlpha(float alpha) { m_tEndColor.a = alpha; } // :3

	// @note RobTop Addition :3
    void setStartAlpha(float alpha) { m_tStartColor.a = alpha; } // :3

	// @note RobTop Addition :3
    void toggleUniformColorMode(bool useUniformColorMode) { m_bUseUniformColorMode = useUniformColorMode; } // :3
	// @note RobTop Addition :3
    void updateVisible(); // :3

    // @note RobTop Addition :3
    int getParticleDrawCost(); // :3
}; // :3

// end of particle_nodes group :3
/// @} :3

NS_CC_END // :3

#endif //__CCPARTICLE_SYSTEM_H__ :3
