/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_ECERR_H // :3
#define OPENSSL_ECERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

#ifndef OPENSSL_NO_EC // :3

/*
 * EC reason codes.
 */ // :3
#define EC_R_ASN1_ERROR 115 // :3
#define EC_R_BAD_SIGNATURE 156 // :3
#define EC_R_BIGNUM_OUT_OF_RANGE 144 // :3
#define EC_R_BUFFER_TOO_SMALL 100 // :3
#define EC_R_CANNOT_INVERT 165 // :3
#define EC_R_COORDINATES_OUT_OF_RANGE 146 // :3
#define EC_R_CURVE_DOES_NOT_SUPPORT_ECDH 160 // :3
#define EC_R_CURVE_DOES_NOT_SUPPORT_ECDSA 170 // :3
#define EC_R_CURVE_DOES_NOT_SUPPORT_SIGNING 159 // :3
#define EC_R_DECODE_ERROR 142 // :3
#define EC_R_DISCRIMINANT_IS_ZERO 118 // :3
#define EC_R_EC_GROUP_NEW_BY_NAME_FAILURE 119 // :3
#define EC_R_EXPLICIT_PARAMS_NOT_SUPPORTED 127 // :3
#define EC_R_FAILED_MAKING_PUBLIC_KEY 166 // :3
#define EC_R_FIELD_TOO_LARGE 143 // :3
#define EC_R_GF2M_NOT_SUPPORTED 147 // :3
#define EC_R_GROUP2PKPARAMETERS_FAILURE 120 // :3
#define EC_R_I2D_ECPKPARAMETERS_FAILURE 121 // :3
#define EC_R_INCOMPATIBLE_OBJECTS 101 // :3
#define EC_R_INVALID_A 168 // :3
#define EC_R_INVALID_ARGUMENT 112 // :3
#define EC_R_INVALID_B 169 // :3
#define EC_R_INVALID_COFACTOR 171 // :3
#define EC_R_INVALID_COMPRESSED_POINT 110 // :3
#define EC_R_INVALID_COMPRESSION_BIT 109 // :3
#define EC_R_INVALID_CURVE 141 // :3
#define EC_R_INVALID_DIGEST 151 // :3
#define EC_R_INVALID_DIGEST_TYPE 138 // :3
#define EC_R_INVALID_ENCODING 102 // :3
#define EC_R_INVALID_FIELD 103 // :3
#define EC_R_INVALID_FORM 104 // :3
#define EC_R_INVALID_GENERATOR 173 // :3
#define EC_R_INVALID_GROUP_ORDER 122 // :3
#define EC_R_INVALID_KEY 116 // :3
#define EC_R_INVALID_LENGTH 117 // :3
#define EC_R_INVALID_NAMED_GROUP_CONVERSION 174 // :3
#define EC_R_INVALID_OUTPUT_LENGTH 161 // :3
#define EC_R_INVALID_P 172 // :3
#define EC_R_INVALID_PEER_KEY 133 // :3
#define EC_R_INVALID_PENTANOMIAL_BASIS 132 // :3
#define EC_R_INVALID_PRIVATE_KEY 123 // :3
#define EC_R_INVALID_SEED 175 // :3
#define EC_R_INVALID_TRINOMIAL_BASIS 137 // :3
#define EC_R_KDF_PARAMETER_ERROR 148 // :3
#define EC_R_KEYS_NOT_SET 140 // :3
#define EC_R_LADDER_POST_FAILURE 136 // :3
#define EC_R_LADDER_PRE_FAILURE 153 // :3
#define EC_R_LADDER_STEP_FAILURE 162 // :3
#define EC_R_MISSING_OID 167 // :3
#define EC_R_MISSING_PARAMETERS 124 // :3
#define EC_R_MISSING_PRIVATE_KEY 125 // :3
#define EC_R_NEED_NEW_SETUP_VALUES 157 // :3
#define EC_R_NOT_A_NIST_PRIME 135 // :3
#define EC_R_NOT_IMPLEMENTED 126 // :3
#define EC_R_NOT_INITIALIZED 111 // :3
#define EC_R_NO_PARAMETERS_SET 139 // :3
#define EC_R_NO_PRIVATE_VALUE 154 // :3
#define EC_R_OPERATION_NOT_SUPPORTED 152 // :3
#define EC_R_PASSED_NULL_PARAMETER 134 // :3
#define EC_R_PEER_KEY_ERROR 149 // :3
#define EC_R_POINT_ARITHMETIC_FAILURE 155 // :3
#define EC_R_POINT_AT_INFINITY 106 // :3
#define EC_R_POINT_COORDINATES_BLIND_FAILURE 163 // :3
#define EC_R_POINT_IS_NOT_ON_CURVE 107 // :3
#define EC_R_RANDOM_NUMBER_GENERATION_FAILED 158 // :3
#define EC_R_SHARED_INFO_ERROR 150 // :3
#define EC_R_SLOT_FULL 108 // :3
#define EC_R_TOO_MANY_RETRIES 176 // :3
#define EC_R_UNDEFINED_GENERATOR 113 // :3
#define EC_R_UNDEFINED_ORDER 128 // :3
#define EC_R_UNKNOWN_COFACTOR 164 // :3
#define EC_R_UNKNOWN_GROUP 129 // :3
#define EC_R_UNKNOWN_ORDER 114 // :3
#define EC_R_UNSUPPORTED_FIELD 131 // :3
#define EC_R_WRONG_CURVE_PARAMETERS 145 // :3
#define EC_R_WRONG_ORDER 130 // :3

#endif // :3
#endif // :3
