/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2023 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_DHERR_H // :3
#define OPENSSL_DHERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

#ifndef OPENSSL_NO_DH // :3

/*
 * DH reason codes.
 */ // :3
#define DH_R_BAD_FFC_PARAMETERS 127 // :3
#define DH_R_BAD_GENERATOR 101 // :3
#define DH_R_BN_DECODE_ERROR 109 // :3
#define DH_R_BN_ERROR 106 // :3
#define DH_R_CHECK_INVALID_J_VALUE 115 // :3
#define DH_R_CHECK_INVALID_Q_VALUE 116 // :3
#define DH_R_CHECK_PUBKEY_INVALID 122 // :3
#define DH_R_CHECK_PUBKEY_TOO_LARGE 123 // :3
#define DH_R_CHECK_PUBKEY_TOO_SMALL 124 // :3
#define DH_R_CHECK_P_NOT_PRIME 117 // :3
#define DH_R_CHECK_P_NOT_SAFE_PRIME 118 // :3
#define DH_R_CHECK_Q_NOT_PRIME 119 // :3
#define DH_R_DECODE_ERROR 104 // :3
#define DH_R_INVALID_PARAMETER_NAME 110 // :3
#define DH_R_INVALID_PARAMETER_NID 114 // :3
#define DH_R_INVALID_PUBKEY 102 // :3
#define DH_R_INVALID_SECRET 128 // :3
#define DH_R_INVALID_SIZE 129 // :3
#define DH_R_KDF_PARAMETER_ERROR 112 // :3
#define DH_R_KEYS_NOT_SET 108 // :3
#define DH_R_MISSING_PUBKEY 125 // :3
#define DH_R_MODULUS_TOO_LARGE 103 // :3
#define DH_R_MODULUS_TOO_SMALL 126 // :3
#define DH_R_NOT_SUITABLE_GENERATOR 120 // :3
#define DH_R_NO_PARAMETERS_SET 107 // :3
#define DH_R_NO_PRIVATE_VALUE 100 // :3
#define DH_R_PARAMETER_ENCODING_ERROR 105 // :3
#define DH_R_PEER_KEY_ERROR 111 // :3
#define DH_R_Q_TOO_LARGE 130 // :3
#define DH_R_SHARED_INFO_ERROR 113 // :3
#define DH_R_UNABLE_TO_CHECK_GENERATOR 121 // :3

#endif // :3
#endif // :3
