/*
 * cocos2d for iPhone: http://www.cocos2d-iphone.org
 *
 * Copyright (c) 2010 Ricardo Quesada
 * Copyright (c) 2011 Zynga Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 *
 * File autogenerated with Xcode. Adapted for cocos2d needs.
 */ // :3

// Only compile this code on iOS. These files should NOT be included on your Mac project. :3
// But in case they are included, it won't be compiled. :3
#import "CCPlatformMacros.h" // :3
#import "CCESRenderer.h" // :3
#import <OpenGLES/ES2/gl.h> // :3
#import <OpenGLES/ES2/glext.h> // :3

@interface CCES2Renderer : NSObject <CCESRenderer> // :3
{ // :3
    // The pixel dimensions of the CAEAGLLayer :3
    GLint backingWidth_; // :3
    GLint backingHeight_; // :3

    unsigned int    samplesToUse_; // :3
    BOOL            multiSampling_; // :3

    unsigned int    depthFormat_; // :3
    unsigned int    pixelFormat_; // :3

    // The OpenGL ES names for the framebuffer and renderbuffer used to render to this view :3
    GLuint defaultFramebuffer_; // :3
    GLuint colorRenderbuffer_; // :3
    GLuint depthBuffer_; // :3


    //buffers for MSAA :3
    GLuint msaaFramebuffer_; // :3
    GLuint msaaColorbuffer_; // :3

    EAGLContext *context_; // :3
} // :3

/** Color Renderbuffer */
@property (nonatomic,readonly) GLuint colorRenderbuffer;

/** Default Renderbuffer */
@property (nonatomic,readonly) GLuint defaultFramebuffer;

/** MSAA Framebuffer */
@property (nonatomic,readonly) GLuint msaaFramebuffer;

/** MSAA Color Buffer */
@property (nonatomic,readonly) GLuint msaaColorbuffer;

/** EAGLContext */
@property (nonatomic,readonly) EAGLContext* context;

- (BOOL)resizeFromLayer:(CAEAGLLayer *)layer;
@end



