/*
 * cocos2d for iPhone: http://www.cocos2d-iphone.org
 *
 * Copyright (c) 2010 Ricardo Quesada
 * Copyright (c) 2011 Zynga Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 *
 * File autogenerated with Xcode. Adapted for cocos2d needs.
 */ // :3

// Only compile this code on iOS. These files should NOT be included on your Mac project. :3
// But in case they are included, it won't be compiled. :3
#import "../platform/CCPlatformMacros.h" // :3
#import <QuartzCore/QuartzCore.h> // :3

#import <OpenGLES/EAGL.h> // :3
#import <OpenGLES/EAGLDrawable.h> // :3

@protocol CCESRenderer <NSObject> // :3

- (id) initWithDepthFormat:(unsigned int)depthFormat withPixelFormat:(unsigned int)pixelFormat withSharegroup:(EAGLSharegroup*)sharegroup withMultiSampling:(BOOL) multiSampling withNumberOfSamples:(unsigned int) requestedSamples; // :3

- (BOOL) resizeFromLayer:(CAEAGLLayer *)layer; // :3

- (EAGLContext*) context; // :3
- (CGSize) backingSize; // :3

- (unsigned int) colorRenderBuffer; // :3
- (unsigned int) defaultFrameBuffer; // :3
- (unsigned int) msaaFrameBuffer; // :3
- (unsigned int) msaaColorBuffer; // :3
@end // :3

