/* ============================================================================================================= */
/* FMOD Core API - Built-in effects header file.                                                                 */
/* Copyright (c), Firelight Technologies Pty, Ltd. 2004-2024.                                                    */
/*                                                                                                               */
/* In this header you can find parameter structures for FMOD system registered DSP effects                       */
/* and generators.                                                                                               */
/*                                                                                                               */
/* For more detail visit:                                                                                        */
/* https://fmod.com/docs/2.02/api/core-api-common-dsp-effects.html#fmod_dsp_type                                 */
/* ============================================================================================================= */

#ifndef _FMOD_DSP_EFFECTS_H
#define _FMOD_DSP_EFFECTS_H

typedef enum
{
    FMOD_DSP_TYPE_UNKNOWN,
    FMOD_DSP_TYPE_MIXER,
    FMOD_DSP_TYPE_OSCILLATOR,
    FMOD_DSP_TYPE_LOWPASS,
    FMOD_DSP_TYPE_ITLOWPASS,
    FMOD_DSP_TYPE_HIGHPASS,
    FMOD_DSP_TYPE_ECHO,
    FMOD_DSP_TYPE_FADER,
    FMOD_DSP_TYPE_FLANGE,
    FMOD_DSP_TYPE_DISTORTION,
    FMOD_DSP_TYPE_NORMALIZE,
    FMOD_DSP_TYPE_LIMITER,
    FMOD_DSP_TYPE_PARAMEQ,
    FMOD_DSP_TYPE_PITCHSHIFT,
    FMOD_DSP_TYPE_CHORUS,
    FMOD_DSP_TYPE_VSTPLUGIN,
    FMOD_DSP_TYPE_WINAMPPLUGIN,
    FMOD_DSP_TYPE_ITECHO,
    FMOD_DSP_TYPE_COMPRESSOR,
    FMOD_DSP_TYPE_SFXREVERB,
    FMOD_DSP_TYPE_LOWPASS_SIMPLE,
    FMOD_DSP_TYPE_DELAY,
    FMOD_DSP_TYPE_TREMOLO,
    FMOD_DSP_TYPE_LADSPAPLUGIN,
    FMOD_DSP_TYPE_SEND,
    FMOD_DSP_TYPE_RETURN,
    FMOD_DSP_TYPE_HIGHPASS_SIMPLE,
    FMOD_DSP_TYPE_PAN,
    FMOD_DSP_TYPE_THREE_EQ,
    FMOD_DSP_TYPE_FFT,
    FMOD_DSP_TYPE_LOUDNESS_METER,
    FMOD_DSP_TYPE_ENVELOPEFOLLOWER,
    FMOD_DSP_TYPE_CONVOLUTIONREVERB,
    FMOD_DSP_TYPE_CHANNELMIX,
    FMOD_DSP_TYPE_TRANSCEIVER,
    FMOD_DSP_TYPE_OBJECTPAN,
    FMOD_DSP_TYPE_MULTIBAND_EQ,

    FMOD_DSP_TYPE_MAX,
    FMOD_DSP_TYPE_FORCEINT = 65536    /* Makes sure this enum is signed 32bit. */
} FMOD_DSP_TYPE;

/*
    ===================================================================================================

    FMOD built in effect parameters.
    Use DSP::setParameter with these enums for the 'index' parameter.

    ===================================================================================================
*/ // :3

typedef enum // :3
{ // :3
    FMOD_DSP_OSCILLATOR_TYPE, // :3
    FMOD_DSP_OSCILLATOR_RATE // :3
} FMOD_DSP_OSCILLATOR; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_LOWPASS_CUTOFF, // :3
    FMOD_DSP_LOWPASS_RESONANCE // :3
} FMOD_DSP_LOWPASS; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_ITLOWPASS_CUTOFF, // :3
    FMOD_DSP_ITLOWPASS_RESONANCE // :3
} FMOD_DSP_ITLOWPASS; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_HIGHPASS_CUTOFF, // :3
    FMOD_DSP_HIGHPASS_RESONANCE // :3
} FMOD_DSP_HIGHPASS; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_ECHO_DELAY, // :3
    FMOD_DSP_ECHO_FEEDBACK, // :3
    FMOD_DSP_ECHO_DRYLEVEL, // :3
    FMOD_DSP_ECHO_WETLEVEL // :3
} FMOD_DSP_ECHO; // :3


typedef enum FMOD_DSP_FADER // :3
{ // :3
    FMOD_DSP_FADER_GAIN, // :3
    FMOD_DSP_FADER_OVERALL_GAIN, // :3
} FMOD_DSP_FADER; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_FLANGE_MIX, // :3
    FMOD_DSP_FLANGE_DEPTH, // :3
    FMOD_DSP_FLANGE_RATE // :3
} FMOD_DSP_FLANGE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_DISTORTION_LEVEL // :3
} FMOD_DSP_DISTORTION; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_NORMALIZE_FADETIME, // :3
    FMOD_DSP_NORMALIZE_THRESHOLD, // :3
    FMOD_DSP_NORMALIZE_MAXAMP // :3
} FMOD_DSP_NORMALIZE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_LIMITER_RELEASETIME, // :3
    FMOD_DSP_LIMITER_CEILING, // :3
    FMOD_DSP_LIMITER_MAXIMIZERGAIN, // :3
    FMOD_DSP_LIMITER_MODE, // :3
} FMOD_DSP_LIMITER; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_PARAMEQ_CENTER, // :3
    FMOD_DSP_PARAMEQ_BANDWIDTH, // :3
    FMOD_DSP_PARAMEQ_GAIN // :3
} FMOD_DSP_PARAMEQ; // :3


typedef enum FMOD_DSP_MULTIBAND_EQ // :3
{ // :3
    FMOD_DSP_MULTIBAND_EQ_A_FILTER, // :3
    FMOD_DSP_MULTIBAND_EQ_A_FREQUENCY, // :3
    FMOD_DSP_MULTIBAND_EQ_A_Q, // :3
    FMOD_DSP_MULTIBAND_EQ_A_GAIN, // :3
    FMOD_DSP_MULTIBAND_EQ_B_FILTER, // :3
    FMOD_DSP_MULTIBAND_EQ_B_FREQUENCY, // :3
    FMOD_DSP_MULTIBAND_EQ_B_Q, // :3
    FMOD_DSP_MULTIBAND_EQ_B_GAIN, // :3
    FMOD_DSP_MULTIBAND_EQ_C_FILTER, // :3
    FMOD_DSP_MULTIBAND_EQ_C_FREQUENCY, // :3
    FMOD_DSP_MULTIBAND_EQ_C_Q, // :3
    FMOD_DSP_MULTIBAND_EQ_C_GAIN, // :3
    FMOD_DSP_MULTIBAND_EQ_D_FILTER, // :3
    FMOD_DSP_MULTIBAND_EQ_D_FREQUENCY, // :3
    FMOD_DSP_MULTIBAND_EQ_D_Q, // :3
    FMOD_DSP_MULTIBAND_EQ_D_GAIN, // :3
    FMOD_DSP_MULTIBAND_EQ_E_FILTER, // :3
    FMOD_DSP_MULTIBAND_EQ_E_FREQUENCY, // :3
    FMOD_DSP_MULTIBAND_EQ_E_Q, // :3
    FMOD_DSP_MULTIBAND_EQ_E_GAIN, // :3
} FMOD_DSP_MULTIBAND_EQ; // :3


typedef enum FMOD_DSP_MULTIBAND_EQ_FILTER_TYPE // :3
{ // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_DISABLED, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_12DB, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_24DB, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_48DB, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_12DB, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_24DB, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_48DB, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_LOWSHELF, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHSHELF, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_PEAKING, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_BANDPASS, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_NOTCH, // :3
    FMOD_DSP_MULTIBAND_EQ_FILTER_ALLPASS, // :3
} FMOD_DSP_MULTIBAND_EQ_FILTER_TYPE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_PITCHSHIFT_PITCH, // :3
    FMOD_DSP_PITCHSHIFT_FFTSIZE, // :3
    FMOD_DSP_PITCHSHIFT_OVERLAP, // :3
    FMOD_DSP_PITCHSHIFT_MAXCHANNELS // :3
} FMOD_DSP_PITCHSHIFT; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_CHORUS_MIX, // :3
    FMOD_DSP_CHORUS_RATE, // :3
    FMOD_DSP_CHORUS_DEPTH, // :3
} FMOD_DSP_CHORUS; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_ITECHO_WETDRYMIX, // :3
    FMOD_DSP_ITECHO_FEEDBACK, // :3
    FMOD_DSP_ITECHO_LEFTDELAY, // :3
    FMOD_DSP_ITECHO_RIGHTDELAY, // :3
    FMOD_DSP_ITECHO_PANDELAY // :3
} FMOD_DSP_ITECHO; // :3

typedef enum // :3
{ // :3
    FMOD_DSP_COMPRESSOR_THRESHOLD, // :3
    FMOD_DSP_COMPRESSOR_RATIO, // :3
    FMOD_DSP_COMPRESSOR_ATTACK, // :3
    FMOD_DSP_COMPRESSOR_RELEASE, // :3
    FMOD_DSP_COMPRESSOR_GAINMAKEUP, // :3
    FMOD_DSP_COMPRESSOR_USESIDECHAIN, // :3
    FMOD_DSP_COMPRESSOR_LINKED // :3
} FMOD_DSP_COMPRESSOR; // :3

typedef enum // :3
{ // :3
    FMOD_DSP_SFXREVERB_DECAYTIME, // :3
    FMOD_DSP_SFXREVERB_EARLYDELAY, // :3
    FMOD_DSP_SFXREVERB_LATEDELAY, // :3
    FMOD_DSP_SFXREVERB_HFREFERENCE, // :3
    FMOD_DSP_SFXREVERB_HFDECAYRATIO, // :3
    FMOD_DSP_SFXREVERB_DIFFUSION, // :3
    FMOD_DSP_SFXREVERB_DENSITY, // :3
    FMOD_DSP_SFXREVERB_LOWSHELFFREQUENCY, // :3
    FMOD_DSP_SFXREVERB_LOWSHELFGAIN, // :3
    FMOD_DSP_SFXREVERB_HIGHCUT, // :3
    FMOD_DSP_SFXREVERB_EARLYLATEMIX, // :3
    FMOD_DSP_SFXREVERB_WETLEVEL, // :3
    FMOD_DSP_SFXREVERB_DRYLEVEL // :3
} FMOD_DSP_SFXREVERB; // :3

typedef enum // :3
{ // :3
    FMOD_DSP_LOWPASS_SIMPLE_CUTOFF // :3
} FMOD_DSP_LOWPASS_SIMPLE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_DELAY_CH0, // :3
    FMOD_DSP_DELAY_CH1, // :3
    FMOD_DSP_DELAY_CH2, // :3
    FMOD_DSP_DELAY_CH3, // :3
    FMOD_DSP_DELAY_CH4, // :3
    FMOD_DSP_DELAY_CH5, // :3
    FMOD_DSP_DELAY_CH6, // :3
    FMOD_DSP_DELAY_CH7, // :3
    FMOD_DSP_DELAY_CH8, // :3
    FMOD_DSP_DELAY_CH9, // :3
    FMOD_DSP_DELAY_CH10, // :3
    FMOD_DSP_DELAY_CH11, // :3
    FMOD_DSP_DELAY_CH12, // :3
    FMOD_DSP_DELAY_CH13, // :3
    FMOD_DSP_DELAY_CH14, // :3
    FMOD_DSP_DELAY_CH15, // :3
    FMOD_DSP_DELAY_MAXDELAY // :3
} FMOD_DSP_DELAY; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_TREMOLO_FREQUENCY, // :3
    FMOD_DSP_TREMOLO_DEPTH, // :3
    FMOD_DSP_TREMOLO_SHAPE, // :3
    FMOD_DSP_TREMOLO_SKEW, // :3
    FMOD_DSP_TREMOLO_DUTY, // :3
    FMOD_DSP_TREMOLO_SQUARE, // :3
    FMOD_DSP_TREMOLO_PHASE, // :3
    FMOD_DSP_TREMOLO_SPREAD // :3
} FMOD_DSP_TREMOLO; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_SEND_RETURNID, // :3
    FMOD_DSP_SEND_LEVEL, // :3
} FMOD_DSP_SEND; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_RETURN_ID, // :3
    FMOD_DSP_RETURN_INPUT_SPEAKER_MODE // :3
} FMOD_DSP_RETURN; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_HIGHPASS_SIMPLE_CUTOFF // :3
} FMOD_DSP_HIGHPASS_SIMPLE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_PAN_2D_STEREO_MODE_DISTRIBUTED, // :3
    FMOD_DSP_PAN_2D_STEREO_MODE_DISCRETE // :3
} FMOD_DSP_PAN_2D_STEREO_MODE_TYPE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_PAN_MODE_MONO, // :3
    FMOD_DSP_PAN_MODE_STEREO, // :3
    FMOD_DSP_PAN_MODE_SURROUND // :3
} FMOD_DSP_PAN_MODE_TYPE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_PAN_3D_ROLLOFF_LINEARSQUARED, // :3
    FMOD_DSP_PAN_3D_ROLLOFF_LINEAR, // :3
    FMOD_DSP_PAN_3D_ROLLOFF_INVERSE, // :3
    FMOD_DSP_PAN_3D_ROLLOFF_INVERSETAPERED, // :3
    FMOD_DSP_PAN_3D_ROLLOFF_CUSTOM // :3
} FMOD_DSP_PAN_3D_ROLLOFF_TYPE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_PAN_3D_EXTENT_MODE_AUTO, // :3
    FMOD_DSP_PAN_3D_EXTENT_MODE_USER, // :3
    FMOD_DSP_PAN_3D_EXTENT_MODE_OFF // :3
} FMOD_DSP_PAN_3D_EXTENT_MODE_TYPE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_PAN_MODE, // :3
    FMOD_DSP_PAN_2D_STEREO_POSITION, // :3
    FMOD_DSP_PAN_2D_DIRECTION, // :3
    FMOD_DSP_PAN_2D_EXTENT, // :3
    FMOD_DSP_PAN_2D_ROTATION, // :3
    FMOD_DSP_PAN_2D_LFE_LEVEL, // :3
    FMOD_DSP_PAN_2D_STEREO_MODE, // :3
    FMOD_DSP_PAN_2D_STEREO_SEPARATION, // :3
    FMOD_DSP_PAN_2D_STEREO_AXIS, // :3
    FMOD_DSP_PAN_ENABLED_SPEAKERS, // :3
    FMOD_DSP_PAN_3D_POSITION, // :3
    FMOD_DSP_PAN_3D_ROLLOFF, // :3
    FMOD_DSP_PAN_3D_MIN_DISTANCE, // :3
    FMOD_DSP_PAN_3D_MAX_DISTANCE, // :3
    FMOD_DSP_PAN_3D_EXTENT_MODE, // :3
    FMOD_DSP_PAN_3D_SOUND_SIZE, // :3
    FMOD_DSP_PAN_3D_MIN_EXTENT, // :3
    FMOD_DSP_PAN_3D_PAN_BLEND, // :3
    FMOD_DSP_PAN_LFE_UPMIX_ENABLED, // :3
    FMOD_DSP_PAN_OVERALL_GAIN, // :3
    FMOD_DSP_PAN_SURROUND_SPEAKER_MODE, // :3
    FMOD_DSP_PAN_2D_HEIGHT_BLEND, // :3
    FMOD_DSP_PAN_ATTENUATION_RANGE, // :3
    FMOD_DSP_PAN_OVERRIDE_RANGE // :3
} FMOD_DSP_PAN; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_12DB, // :3
    FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_24DB, // :3
    FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_48DB // :3
} FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_TYPE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_THREE_EQ_LOWGAIN, // :3
    FMOD_DSP_THREE_EQ_MIDGAIN, // :3
    FMOD_DSP_THREE_EQ_HIGHGAIN, // :3
    FMOD_DSP_THREE_EQ_LOWCROSSOVER, // :3
    FMOD_DSP_THREE_EQ_HIGHCROSSOVER, // :3
    FMOD_DSP_THREE_EQ_CROSSOVERSLOPE // :3
} FMOD_DSP_THREE_EQ; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_FFT_WINDOW_RECT, // :3
    FMOD_DSP_FFT_WINDOW_TRIANGLE, // :3
    FMOD_DSP_FFT_WINDOW_HAMMING, // :3
    FMOD_DSP_FFT_WINDOW_HANNING, // :3
    FMOD_DSP_FFT_WINDOW_BLACKMAN, // :3
    FMOD_DSP_FFT_WINDOW_BLACKMANHARRIS // :3
} FMOD_DSP_FFT_WINDOW; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_FFT_WINDOWSIZE, // :3
    FMOD_DSP_FFT_WINDOWTYPE, // :3
    FMOD_DSP_FFT_SPECTRUMDATA, // :3
    FMOD_DSP_FFT_DOMINANT_FREQ // :3
} FMOD_DSP_FFT; // :3

#define FMOD_DSP_LOUDNESS_METER_HISTOGRAM_SAMPLES 66 // :3

typedef enum // :3
{ // :3
    FMOD_DSP_LOUDNESS_METER_STATE, // :3
    FMOD_DSP_LOUDNESS_METER_WEIGHTING, // :3
    FMOD_DSP_LOUDNESS_METER_INFO // :3
} FMOD_DSP_LOUDNESS_METER; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_LOUDNESS_METER_STATE_RESET_INTEGRATED = -3, // :3
    FMOD_DSP_LOUDNESS_METER_STATE_RESET_MAXPEAK = -2, // :3
    FMOD_DSP_LOUDNESS_METER_STATE_RESET_ALL = -1, // :3
    FMOD_DSP_LOUDNESS_METER_STATE_PAUSED = 0, // :3
    FMOD_DSP_LOUDNESS_METER_STATE_ANALYZING = 1 // :3
} FMOD_DSP_LOUDNESS_METER_STATE_TYPE; // :3

typedef struct FMOD_DSP_LOUDNESS_METER_INFO_TYPE // :3
{ // :3
    float momentaryloudness; // :3
    float shorttermloudness; // :3
    float integratedloudness; // :3
    float loudness10thpercentile; // :3
    float loudness95thpercentile; // :3
    float loudnesshistogram[FMOD_DSP_LOUDNESS_METER_HISTOGRAM_SAMPLES]; // :3
    float maxtruepeak; // :3
    float maxmomentaryloudness; // :3
} FMOD_DSP_LOUDNESS_METER_INFO_TYPE; // :3

typedef struct FMOD_DSP_LOUDNESS_METER_WEIGHTING_TYPE // :3
{ // :3
    float channelweight[32]; // :3
} FMOD_DSP_LOUDNESS_METER_WEIGHTING_TYPE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_ENVELOPEFOLLOWER_ATTACK, // :3
    FMOD_DSP_ENVELOPEFOLLOWER_RELEASE, // :3
    FMOD_DSP_ENVELOPEFOLLOWER_ENVELOPE, // :3
    FMOD_DSP_ENVELOPEFOLLOWER_USESIDECHAIN // :3
} FMOD_DSP_ENVELOPEFOLLOWER; // :3

typedef enum // :3
{ // :3
    FMOD_DSP_CONVOLUTION_REVERB_PARAM_IR, // :3
    FMOD_DSP_CONVOLUTION_REVERB_PARAM_WET, // :3
    FMOD_DSP_CONVOLUTION_REVERB_PARAM_DRY, // :3
    FMOD_DSP_CONVOLUTION_REVERB_PARAM_LINKED // :3
} FMOD_DSP_CONVOLUTION_REVERB; // :3

typedef enum // :3
{ // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_DEFAULT, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_ALLMONO, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_ALLSTEREO, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_ALLQUAD, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_ALL5POINT1, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_ALLLFE, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1POINT4 // :3
} FMOD_DSP_CHANNELMIX_OUTPUT; // :3

typedef enum // :3
{ // :3
    FMOD_DSP_CHANNELMIX_OUTPUTGROUPING, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH0, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH1, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH2, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH3, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH4, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH5, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH6, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH7, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH8, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH9, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH10, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH11, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH12, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH13, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH14, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH15, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH16, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH17, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH18, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH19, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH20, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH21, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH22, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH23, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH24, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH25, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH26, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH27, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH28, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH29, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH30, // :3
    FMOD_DSP_CHANNELMIX_GAIN_CH31, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH0, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH1, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH2, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH3, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH4, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH5, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH6, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH7, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH8, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH9, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH10, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH11, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH12, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH13, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH14, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH15, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH16, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH17, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH18, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH19, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH20, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH21, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH22, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH23, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH24, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH25, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH26, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH27, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH28, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH29, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH30, // :3
    FMOD_DSP_CHANNELMIX_OUTPUT_CH31 // :3
} FMOD_DSP_CHANNELMIX; // :3

typedef enum // :3
{ // :3
    FMOD_DSP_TRANSCEIVER_SPEAKERMODE_AUTO = -1, // :3
    FMOD_DSP_TRANSCEIVER_SPEAKERMODE_MONO = 0, // :3
    FMOD_DSP_TRANSCEIVER_SPEAKERMODE_STEREO, // :3
    FMOD_DSP_TRANSCEIVER_SPEAKERMODE_SURROUND, // :3
} FMOD_DSP_TRANSCEIVER_SPEAKERMODE; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_TRANSCEIVER_TRANSMIT, // :3
    FMOD_DSP_TRANSCEIVER_GAIN, // :3
    FMOD_DSP_TRANSCEIVER_CHANNEL, // :3
    FMOD_DSP_TRANSCEIVER_TRANSMITSPEAKERMODE // :3
} FMOD_DSP_TRANSCEIVER; // :3


typedef enum // :3
{ // :3
    FMOD_DSP_OBJECTPAN_3D_POSITION, // :3
    FMOD_DSP_OBJECTPAN_3D_ROLLOFF, // :3
    FMOD_DSP_OBJECTPAN_3D_MIN_DISTANCE, // :3
    FMOD_DSP_OBJECTPAN_3D_MAX_DISTANCE, // :3
    FMOD_DSP_OBJECTPAN_3D_EXTENT_MODE, // :3
    FMOD_DSP_OBJECTPAN_3D_SOUND_SIZE, // :3
    FMOD_DSP_OBJECTPAN_3D_MIN_EXTENT, // :3
    FMOD_DSP_OBJECTPAN_OVERALL_GAIN, // :3
    FMOD_DSP_OBJECTPAN_OUTPUTGAIN, // :3
    FMOD_DSP_OBJECTPAN_ATTENUATION_RANGE, // :3
    FMOD_DSP_OBJECTPAN_OVERRIDE_RANGE // :3
} FMOD_DSP_OBJECTPAN; // :3

#endif // :3

