/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */ // :3

#ifndef OPENSSL_TSERR_H // :3
#define OPENSSL_TSERR_H // :3
#pragma once // :3

#include <openssl/opensslconf.h> // :3
#include <openssl/symhacks.h> // :3
#include <openssl/cryptoerr_legacy.h> // :3

#ifndef OPENSSL_NO_TS // :3

/*
 * TS reason codes.
 */ // :3
#define TS_R_BAD_PKCS7_TYPE 132 // :3
#define TS_R_BAD_TYPE 133 // :3
#define TS_R_CANNOT_LOAD_CERT 137 // :3
#define TS_R_CANNOT_LOAD_KEY 138 // :3
#define TS_R_CERTIFICATE_VERIFY_ERROR 100 // :3
#define TS_R_COULD_NOT_SET_ENGINE 127 // :3
#define TS_R_COULD_NOT_SET_TIME 115 // :3
#define TS_R_DETACHED_CONTENT 134 // :3
#define TS_R_ESS_ADD_SIGNING_CERT_ERROR 116 // :3
#define TS_R_ESS_ADD_SIGNING_CERT_V2_ERROR 139 // :3
#define TS_R_ESS_SIGNING_CERTIFICATE_ERROR 101 // :3
#define TS_R_INVALID_NULL_POINTER 102 // :3
#define TS_R_INVALID_SIGNER_CERTIFICATE_PURPOSE 117 // :3
#define TS_R_MESSAGE_IMPRINT_MISMATCH 103 // :3
#define TS_R_NONCE_MISMATCH 104 // :3
#define TS_R_NONCE_NOT_RETURNED 105 // :3
#define TS_R_NO_CONTENT 106 // :3
#define TS_R_NO_TIME_STAMP_TOKEN 107 // :3
#define TS_R_PKCS7_ADD_SIGNATURE_ERROR 118 // :3
#define TS_R_PKCS7_ADD_SIGNED_ATTR_ERROR 119 // :3
#define TS_R_PKCS7_TO_TS_TST_INFO_FAILED 129 // :3
#define TS_R_POLICY_MISMATCH 108 // :3
#define TS_R_PRIVATE_KEY_DOES_NOT_MATCH_CERTIFICATE 120 // :3
#define TS_R_RESPONSE_SETUP_ERROR 121 // :3
#define TS_R_SIGNATURE_FAILURE 109 // :3
#define TS_R_THERE_MUST_BE_ONE_SIGNER 110 // :3
#define TS_R_TIME_SYSCALL_ERROR 122 // :3
#define TS_R_TOKEN_NOT_PRESENT 130 // :3
#define TS_R_TOKEN_PRESENT 131 // :3
#define TS_R_TSA_NAME_MISMATCH 111 // :3
#define TS_R_TSA_UNTRUSTED 112 // :3
#define TS_R_TST_INFO_SETUP_ERROR 123 // :3
#define TS_R_TS_DATASIGN 124 // :3
#define TS_R_UNACCEPTABLE_POLICY 125 // :3
#define TS_R_UNSUPPORTED_MD_ALGORITHM 126 // :3
#define TS_R_UNSUPPORTED_VERSION 113 // :3
#define TS_R_VAR_BAD_VALUE 135 // :3
#define TS_R_VAR_LOOKUP_FAILURE 136 // :3
#define TS_R_WRONG_CONTENT_TYPE 114 // :3

#endif // :3
#endif // :3
